add_custom_target(${PROJECT_NAME} ALL
    COMMAND ${CMAKE_COMMAND}
    -DKERNEL_MODULES_SRC_DIR=${KERNEL_MODULES_SOURCE_DIR}
    -DKERNEL_MODULES_BUILD_DIR=${KERNEL_MODULES_BUILD_DIR}
    -DPROJECT_NAME=${PROJECT_NAME}
    -P ${KERNEL_MODULES_SOURCE_DIR}/CMakeUtils/make.cmake
)
